<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
                  xmlns:tns="http://vrk-test.x-road.fi/producer" 
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
                  xmlns:xrd="http://x-road.eu/xsd/xroad.xsd"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:id="http://x-road.eu/xsd/identifiers"
                  name="provider-gateway" targetNamespace="http://vrk-test.x-road.fi/producer">
    <wsdl:types>
        <xsd:schema elementFormDefault="qualified" targetNamespace="http://vrk-test.x-road.fi/producer">
            <!-- Import X-Road schema -->
            <xsd:import id="xrd" namespace="http://x-road.eu/xsd/xroad.xsd" schemaLocation="http://x-road.eu/xsd/xroad.xsd"/>
            
            
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="requestheader">
        <wsdl:part name="client" element="xrd:client" />
        <wsdl:part name="service" element="xrd:service" />
        <wsdl:part name="userId" element="xrd:userId" />
        <wsdl:part name="id" element="xrd:id" />
        <wsdl:part name="issue" element="xrd:issue" />
        <wsdl:part name="protocolVersion" element="xrd:protocolVersion" />
    </wsdl:message>


    <wsdl:portType name="xRoadPortType">
    </wsdl:portType>

    <wsdl:binding name="xRoadBinding" type="tns:xRoadPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        
    </wsdl:binding>

    <wsdl:service name="provider-gateway">
        <wsdl:port binding="tns:xRoadBinding" name="xRoadServicePort">
            <soap:address location="http://{HOST}/Provider"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
